CREATE DATABASE 'ERP.fdb' USER 'sysdba' PASSWORD 'masterkey';

CREATE TABLE usuario (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpf VARCHAR(50),
  usuario VARCHAR(255),
  senha VARCHAR(25)
);

CREATE TABLE produto (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  preco_unit DECIMAL(10,2),
  quantidade_estoque INTEGER
);

CREATE TABLE cliente (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  cpf_cnpj VARCHAR(50)
);

CREATE TABLE pedido (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INTEGER,
  usuario_id INTEGER,
  data_pedido DATE,
  total DECIMAL(10,2),
  FOREIGN KEY (cliente_id) REFERENCES cliente (id),
  FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE pedido_produto (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id INTEGER,
  produto_id INTEGER,
  quantidade INTEGER,
  FOREIGN KEY (pedido_id) REFERENCES pedido (id),
  FOREIGN KEY (produto_id) REFERENCES produto (id)
);
