SELECT 
  C.NOME, 
  SUM(P.TOTAL) AS VALOR_GASTO,
  COUNT(P.ID) AS QUANTIDADE_PEDIDOS,
  U.USUARIO AS VENDEDOR
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.ID = P.CLIENTE_ID
INNER JOIN USUARIO U ON U.ID = P.USUARIO_ID
GROUP BY C.ID, C.NOME, U.USUARIO;

SELECT 
    P.ID, 
    P.DATA_PEDIDO, 
    P.TOTAL,
    C.NOME AS CLIENTE,
    U.USUARIO AS VENDEDOR
FROM PEDIDO P
INNER JOIN USUARIO U ON U.ID = P.USUARIO_ID
INNER JOIN CLIENTE C ON C.ID = P.CLIENTE_ID
GROUP BY C.ID, C.NOME, U.USUARIO;
ORDER BY P.DATA_PEDIDO DESC; 