SELECT 
  C.NOME, 
  SUM(P.TOTAL) AS VALOR_GASTO,
  COUNT(P.ID) AS QUANTIDADE_PEDIDOS,
  U.USUARIO AS VENDEDOR
FROM PEDIDO P
INNER JOIN CLIENTE C ON C.ID = P.CLIENTE_ID
INNER JOIN USUARIO U ON U.ID = P.USUARIO_ID
GROUP BY C.ID, C.NOME, U.USUARIO;

SELECT 
    P.ID, 
    P.DATA_PEDIDO, 
    P.TOTAL,
    C.NOME AS CLIENTE,
    U.USUARIO AS VENDEDOR
FROM PEDIDO P
INNER JOIN USUARIO U ON U.ID = P.USUARIO_ID
INNER JOIN CLIENTE C ON C.ID = P.CLIENTE_ID
ORDER BY P.DATA_PEDIDO DESC; 

SELECT 
    P.NOME AS PRODUTO,
    SUM(PP.QUANTIDADE) AS TOTAL_VENDIDOS
FROM PEDIDO_PRODUTO PP
INNER JOIN PRODUTO P ON P.ID = PP.PRODUTO_ID
GROUP BY P.NOME
ORDER BY TOTAL_VENDIDOS DESC;

SELECT ID,NOME,QUANTIDADE_ESTOQUE  FROM PRODUTO 
WHERE QUANTIDADE_ESTOQUE <= 0
